import type { PreviewParams } from '../../../src/core/types';
import { defaultPreviewParams } from '../../../src/shared/preview/shader-preview';

export const PRESETS: Record<string, () => PreviewParams> = {
  noon: () => ({ ...defaultPreviewParams(), timeOfDay: 6000 }),
  default: () => defaultPreviewParams(),
  sunset: () => ({
    ...defaultPreviewParams(),
    timeOfDay: 11850,
    sunColor: [1, 0.78, 0.55],
    skyTop: [0.28, 0.42, 0.78],
    skyHorizon: [0.95, 0.7, 0.5],
    fogColor: [0.9, 0.7, 0.55],
    fogDensity: 0.35,
    godrays: 0.85,
    bloom: 0.6,
    contrast: 1.1,
    saturation: 1.12,
    vignette: 0.45,
    temperature: 0.25,
    exposure: 1.05,
  }),
  night: () => ({ ...defaultPreviewParams(), timeOfDay: 18000, bloom: 0.55, godrays: 0.3, fogDensity: 0.25, vignette: 0.4 }),
  noir: () => ({
    ...defaultPreviewParams(),
    timeOfDay: 4200,
    grayscale: 1,
    contrast: 1.35,
    vignette: 0.65,
    fogDensity: 0.45,
    bloom: 0.25,
    godrays: 0.5,
    exposure: 0.95,
  }),
  vivid: () => ({
    ...defaultPreviewParams(),
    timeOfDay: 4300,
    saturation: 1.35,
    contrast: 1.12,
    bloom: 0.4,
    godrays: 0.45,
    skyTop: [0.18, 0.48, 1],
    skyHorizon: [0.62, 0.86, 1],
    waterColor: [0.1, 0.62, 0.9],
    waterClarity: 0.8,
    waving: 0.8,
    fogDensity: 0.15,
  }),
  retro: () => ({ ...defaultPreviewParams(), posterize: 6, sepia: 0.5, vignette: 0.5, bloom: 0.1, godrays: 0 }),
  flat: () => ({ ...defaultPreviewParams(), bloom: 0, godrays: 0, vignette: 0, fogDensity: 0, shadowStrength: 0, waving: 0 }),
};
