// Iris / OptiFine shader pack generator: pack layout, settings.glsl, shaders.properties, lang,
// block/item/entity IDs and the zip. GLSL compilation is covered by iris-glsl.test.ts.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { unzipSync, strFromU8 } from 'fflate';

import {
  GAME_OPTIONS, IRIS_IDS, IRIS_PROGRAMS, PRESETS, PROFILES, SCREENS, defaults, generateIrisPack, irisPackFileName, presetValues,
  readSettings, zipIrisPack,
} from '../../src/tools/shaders/iris/index';
import { formatValue, optionList } from '../../src/tools/shaders/iris/game-options';
import { writeZip, readZip } from '../../src/core/zip';
import type { OptionValues } from '../../src/core/types';
import { expandIncludes, lintShadersProperties, parsePackOptions, propertyLines, varyings, checkVaryings, ENVIRONMENTS, injectMacros } from '../tools/iris/glsl-check';
import { preprocessProperties, propertiesFor } from '../tools/iris/properties';
import { allExtreme, mulberry32, randomOptions } from '../tools/iris/fixtures';

const META = { name: 'Test Pack', description: 'A pack for tests.' };
type Files = Record<string, string>;

function gen(v: OptionValues, meta = META): Files {
  const files = generateIrisPack(v, meta);
  for (const [p, c] of Object.entries(files)) assert.equal(typeof c, 'string', `${p} is text`);
  return files as Files;
}

/** Every option combination the tests look at. */
function variants(): Array<[string, OptionValues]> {
  const out: Array<[string, OptionValues]> = [['defaults', defaults()]];
  for (const p of PRESETS) out.push([`preset ${p.id}`, presetValues(p.id)]);
  out.push(['all minimum', allExtreme(false)], ['all maximum', allExtreme(true)]);
  const rand = mulberry32(2024);
  for (let i = 0; i < 12; i++) out.push([`random ${i}`, randomOptions(rand, i % 2 === 0)]);
  return out;
}

const shaderFiles = (files: Files): string[] => Object.keys(files).filter((p) => p.startsWith('shaders/'));

test('pack layout: README at the root, everything else under shaders/', () => {
  const files = gen(defaults());
  const paths = Object.keys(files);
  assert.ok(paths.includes('README.txt'));
  for (const p of paths) assert.ok(p === 'README.txt' || p.startsWith('shaders/'), `unexpected path ${p}`);
  for (const p of ['shaders.properties', 'block.properties', 'item.properties', 'entity.properties', 'lang/en_US.lang',
    'lib/settings.glsl', 'lib/uniforms.glsl', 'lib/common.glsl', 'lib/sky.glsl', 'lib/fog.glsl', 'lib/waving.glsl', 'lib/distort.glsl',
    'lib/shadows.glsl', 'lib/lighting.glsl']) {
    assert.ok(files[`shaders/${p}`], `missing shaders/${p}`);
  }
  const required = ['gbuffers_basic', 'gbuffers_textured', 'gbuffers_skybasic', 'gbuffers_skytextured', 'gbuffers_clouds',
    'gbuffers_terrain', 'gbuffers_water', 'gbuffers_block', 'gbuffers_entities', 'gbuffers_hand', 'gbuffers_weather',
    'gbuffers_damagedblock', 'gbuffers_beaconbeam', 'gbuffers_armor_glint', 'gbuffers_spidereyes', 'shadow', 'composite',
    'composite1', 'final'];
  assert.deepEqual([...IRIS_PROGRAMS].sort(), [...required].sort());
  for (const prog of required) {
    assert.ok(files[`shaders/${prog}.vsh`] && files[`shaders/${prog}.fsh`], `${prog}: vertex + fragment shader`);
  }
  // Old OptiFine only knows composite..composite7.
  assert.ok(!paths.some((p) => /composite([89]|\d\d)\./.test(p)));
});

test('text files are ASCII (GLSL, .properties); the name only reaches UTF-8 files', () => {
  const files = gen(defaults(), { name: 'Crème Brûlée ✨ 100%', description: 'Ünïcödé \\ desc %s\nsecond line' });
  for (const [p, c] of Object.entries(files)) {
    if (/\.(glsl|vsh|fsh|properties)$/.test(p)) assert.match(c, /^[\x09\x0a\x20-\x7e]*$/, `${p} must be ASCII`);
    assert.ok(!c.includes('\r'), `${p}: LF line endings`);
  }
  const lang = files['shaders/lang/en_US.lang'];
  assert.ok(lang.includes('option.PACK_INFO=Crème Brûlée ✨ 100\n'), 'lang keeps the name (UTF-8) without % or \\');
  assert.ok(lang.includes('option.PACK_INFO.comment=Ünïcödé desc s second line Made with TexturesOnline.'));
  assert.ok(files['shaders/shaders.properties'].startsWith('# Creme Brulee 100 - Made with TexturesOnline.'));
  assert.ok(files['README.txt'].startsWith('Crème Brûlée ✨ 100\n'));
});

test('no forbidden words anywhere (generated files and generator sources)', () => {
  const bad = /\b(openai|chatgpt|gpt-\d|artificial intelligence|a\.i\.|ai[- ]generated|generated by ai)\b|\bAI\b/i;
  for (const [name, v] of variants().slice(0, 4)) {
    for (const [p, c] of Object.entries(gen(v))) assert.ok(!bad.test(c), `${name}: ${p}`);
  }
  const dir = fileURLToPath(new URL('../../src/tools/shaders/iris/', import.meta.url));
  for (const f of readdirSync(dir)) {
    assert.ok(!bad.test(readFileSync(dir + f, 'utf8')), `src/tools/shaders/iris/${f}`);
  }
  const files = gen(defaults());
  assert.ok(files['README.txt'].includes('Made with TexturesOnline'));
  assert.ok(files['shaders/lang/en_US.lang'].includes('Made with TexturesOnline'));
});

test('includes resolve, each lib once per program, no include guards', () => {
  const files = gen(defaults());
  const rel: Files = {};
  for (const [p, c] of Object.entries(files)) if (p.startsWith('shaders/')) rel[p.slice('shaders/'.length)] = c;
  for (const p of Object.keys(rel).filter((x) => /\.(vsh|fsh)$/.test(x))) {
    assert.match(rel[p], /^#version 120\n/, `${p}: #version 120 first`);
    const incs = [...rel[p].matchAll(/#include "([^"]+)"/g)].map((m) => m[1]);
    assert.equal(new Set(incs).size, incs.length, `${p}: a lib included twice`);
    for (const lib of incs) assert.ok(rel[lib.replace(/^\//, '')], `${p}: missing ${lib}`);
    const expanded = expandIncludes(rel, p);
    assert.ok(!/#include/.test(expanded));
    // gl_FragData index is always a literal and every write sits on its own line (OptiFine rewrites line by line).
    for (const line of expanded.split('\n')) {
      if (line.includes('gl_FragData')) assert.match(line.trim(), /^gl_FragData\[\d\] = .+;$/, `${p}: ${line.trim()}`);
    }
    assert.ok(!/\b(iris_\w+|irisMain|moj_import|outColor\d|temp_FragData)/.test(expanded), `${p}: reserved identifier`);
    assert.ok(!/\bgl_FragColor\b/.test(expanded), `${p}: uses gl_FragData only`);
    if (p.endsWith('.fsh') && p !== 'final.fsh') {
      const draw = [...expanded.matchAll(/\/\*\s*DRAWBUFFERS:(\d+)\s*\*\//g)];
      assert.equal(draw.length, 1, `${p}: one DRAWBUFFERS directive`);
      const outputs = new Set([...expanded.matchAll(/gl_FragData\[(\d)\]/g)].map((m) => Number(m[1])));
      assert.equal(Math.max(...outputs) + 1, draw[0][1].length, `${p}: outputs match DRAWBUFFERS`);
    }
  }
  for (const [p, c] of Object.entries(rel)) {
    if (!p.endsWith('.glsl')) continue;
    assert.ok(!/#ifndef\s+\w+\s*\n\s*#define\s+\1/.test(c), `${p}: include guard`);
  }
});

test('varyings match between vertex and fragment shaders', () => {
  const files = gen(defaults());
  const rel: Files = {};
  for (const [p, c] of Object.entries(files)) if (p.startsWith('shaders/')) rel[p.slice('shaders/'.length)] = c;
  for (const prog of IRIS_PROGRAMS) {
    for (const env of ENVIRONMENTS) {
      const v = injectMacros(expandIncludes(rel, `${prog}.vsh`), env.macros);
      const f = injectMacros(expandIncludes(rel, `${prog}.fsh`), env.macros);
      assert.deepEqual(checkVaryings(v, f), [], `${prog} (${env.name})`);
      assert.ok(varyings(f).size > 0 || prog === 'final', `${prog}: has inputs`);
    }
  }
});

test('settings.glsl: every in-game option, chosen values inside their sorted lists', () => {
  for (const [name, v] of variants()) {
    const files = gen(v);
    const settings = files['shaders/lib/settings.glsl'];
    const opts = parsePackOptions(files);
    assert.deepEqual(opts.problems, [], `${name}: option problems`);
    const s = readSettings(v);
    for (const opt of GAME_OPTIONS) {
      if (opt.kind === 'bool') {
        assert.equal(opts.bools.get(opt.name), opt.value(s), `${name}: ${opt.name}`);
        continue;
      }
      const parsed = opts.values.get(opt.name);
      assert.ok(parsed, `${name}: ${opt.name} declared`);
      const expected = formatValue(opt.value(s), opt.decimals);
      assert.equal(parsed.value, expected, `${name}: ${opt.name} default`);
      assert.ok(parsed.list.includes(expected), `${name}: ${opt.name} list contains the chosen value`);
      const nums = parsed.list.map(Number);
      assert.deepEqual([...nums].sort((a, b) => a - b), nums, `${name}: ${opt.name} list sorted`);
      for (const item of parsed.list) assert.match(item, opt.decimals ? new RegExp(`^-?\\d+\\.\\d{${opt.decimals}}$`) : /^-?\d+$/);
      assert.deepEqual(optionList(opt, s).list, parsed.list);
    }
    assert.equal(opts.bools.size + opts.values.size, GAME_OPTIONS.length, `${name}: no stray options`);
    // Const directives the loaders need are present exactly once.
    for (const c of ['shadowMapResolution', 'shadowDistance', 'sunPathRotation', 'shadowHardwareFiltering', 'shadowDistanceRenderMul']) {
      assert.equal(settings.split(`const `).filter((x) => x.includes(` ${c} =`)).length, 1, `${name}: const ${c}`);
    }
  }
});

test('settings.glsl: web values map onto the in-game options', () => {
  const pick = (v: OptionValues, n: string): string | boolean | undefined => {
    const o = parsePackOptions(gen(v));
    return o.bools.has(n) ? o.bools.get(n) : o.values.get(n)?.value;
  };
  const d = defaults();
  assert.equal(pick({ ...d, bloomStrength: 0 }, 'BLOOM'), false);
  assert.equal(pick({ ...d, bloomStrength: 0 }, 'BLOOM_STRENGTH'), '0.20', 'switched-off bloom keeps a useful in-game strength');
  assert.equal(pick({ ...d, bloomStrength: 0.35 }, 'BLOOM_STRENGTH'), '0.35');
  assert.equal(pick({ ...d, godrays: 0 }, 'GODRAYS'), false);
  assert.equal(pick({ ...d, godrays: 1.25 }, 'GODRAYS_STRENGTH'), '1.25');
  assert.equal(pick({ ...d, tonemap: 'none' }, 'TONEMAP'), '0');
  assert.equal(pick({ ...d, tonemap: 'reinhard' }, 'TONEMAP'), '1');
  assert.equal(pick({ ...d, tonemap: 'aces' }, 'TONEMAP'), '2');
  assert.equal(pick({ ...d, tonemap: 'filmic' }, 'TONEMAP'), '3');
  assert.equal(pick({ ...d, sunAngle: 25 }, 'sunPathRotation'), '25.0');
  assert.equal(pick({ ...d, shadowDistance: 208 }, 'shadowDistance'), '208.0');
  assert.equal(pick({ ...d, shadowResolution: '8192' }, 'shadowMapResolution'), '8192');
  assert.equal(pick({ ...d, effectQuality: 'ultra' }, 'SHADOW_SAMPLES'), '24');
  assert.equal(pick({ ...d, effectQuality: 'low' }, 'GODRAYS_SAMPLES'), '8');
  assert.equal(pick({ ...d, waterColor: '#ff8000' }, 'WATER_G'), '0.50');
  assert.equal(pick({ ...d, exposure: -0.35 }, 'EXPOSURE'), '-0.35');
  assert.equal(pick({ ...d, temperature: -0.001 }, 'TEMPERATURE'), '0.00');
  assert.equal(pick({ ...d, shadows: false }, 'SHADOWS'), false);
  assert.equal(pick({ ...d, handLight: false }, 'HAND_LIGHT'), false);
  assert.equal(pick({ ...d, cloudShadows: true }, 'CLOUD_SHADOWS'), true);
  assert.equal(pick({ ...d, wavingVines: false }, 'WAVING_VINES'), false);
  assert.equal(pick({ ...d, waterWaves: false }, 'WATER_WAVES'), false);
  const settings = gen({ ...d, cloudShadows: false })['shaders/lib/settings.glsl'];
  assert.ok(settings.includes('\n//#define CLOUD_SHADOWS // '));
  assert.ok(settings.includes('\n#define SHADOWS // '));
});

test('shaders.properties: screens, sliders and profiles only use real options', () => {
  for (const [name, v] of variants()) {
    const files = gen(v);
    const opts = parsePackOptions(files);
    const text = files['shaders/shaders.properties'];
    assert.deepEqual(lintShadersProperties(text, opts), [], name);
    for (const env of ENVIRONMENTS) {
      const macros: Record<string, string> = { ...env.macros };
      for (const [b, on] of opts.bools) if (on) macros[b] = '';
      assert.doesNotThrow(() => preprocessProperties(text, macros), `${name}: balanced #if in ${env.name}`);
    }
  }
  const files = gen(defaults());
  const text = files['shaders/shaders.properties'];
  const props = new Map(propertyLines(text));
  const opts = parsePackOptions(files);
  // Every option is reachable on exactly one screen.
  const placed = [...props.entries()].filter(([k]) => k === 'screen' || (k.startsWith('screen.') && !k.endsWith('.columns')))
    .flatMap(([, v]) => v.split(/\s+/)).filter((x) => /^[A-Za-z]/.test(x));
  assert.deepEqual([...placed].sort(), GAME_OPTIONS.map((o) => o.name).sort());
  // Sliders: every value option with more than a handful of values.
  const sliders = props.get('sliders')!.split(' ');
  for (const [n, o] of opts.values) {
    if (n === 'PACK_INFO' || n === 'TONEMAP') assert.ok(!sliders.includes(n));
    else assert.ok(sliders.includes(n), `${n} is a slider`);
    void o;
  }
  // Profiles set the same options, and the default web settings match the Medium profile.
  const profileKeys = PROFILES.map((p) => p.items.map((i) => i.replace(/^!/, '').split('=')[0]).sort().join(' '));
  assert.equal(new Set(profileKeys).size, 1);
  const medium = PROFILES.find((p) => p.id === 'MEDIUM')!;
  for (const item of medium.items) {
    if (item.includes('=')) {
      const [n, val] = item.split('=');
      assert.equal(opts.values.get(n)!.value, val, `MEDIUM ${n}`);
    } else {
      assert.equal(opts.bools.get(item.replace(/^!/, '')), !item.startsWith('!'), `MEDIUM ${item}`);
    }
  }
  assert.equal(props.get('program.shadow.enabled'), 'SHADOWS');
  assert.equal(props.get('program.composite1.enabled'), 'BLOOM');
  assert.equal(props.get('oldLighting'), 'false');
  assert.equal(props.get('underwaterOverlay'), 'false');
});

test('lang/en_US.lang: readable names for every option, screen, profile and enum value', () => {
  for (const [name, v] of variants().slice(0, 12)) {
    const files = gen(v);
    const lang = files['shaders/lang/en_US.lang'];
    const entries = new Map<string, string>();
    for (const line of lang.split('\n')) {
      if (!line || line.startsWith('#')) continue;
      assert.match(line, /^[\w.\-]+=\S/, `${name}: key=value with no spaces around '=' (${line})`);
      assert.ok(!/[%\\]/.test(line), `${name}: no % or \\ (${line})`);
      const i = line.indexOf('=');
      assert.ok(!entries.has(line.slice(0, i)), `${name}: duplicate key ${line.slice(0, i)}`);
      entries.set(line.slice(0, i), line.slice(i + 1));
    }
    const opts = parsePackOptions(files);
    for (const n of [...opts.bools.keys(), ...opts.values.keys()]) {
      assert.ok(entries.get(`option.${n}`), `${name}: option.${n}`);
      assert.ok(entries.get(`option.${n}.comment`), `${name}: option.${n}.comment`);
    }
    for (const sc of SCREENS) assert.ok(entries.get(`screen.${sc.id}`) && entries.get(`screen.${sc.id}.comment`), `${name}: screen.${sc.id}`);
    for (const p of PROFILES) assert.ok(entries.get(`profile.${p.id}`), `${name}: profile.${p.id}`);
    assert.ok(entries.get('profile.comment'));
    for (const t of ['0', '1', '2', '3']) assert.ok(entries.get(`value.TONEMAP.${t}`));
    for (const val of opts.values.get('shadowDistance')!.list) assert.ok(entries.get(`value.shadowDistance.${val}`), `${name}: shadowDistance ${val}`);
    for (const val of opts.values.get('SHADOW_SAMPLES')!.list) assert.ok(entries.get(`value.SHADOW_SAMPLES.${val}`));
    assert.equal(entries.get('option.PACK_INFO'), 'Test Pack');
    assert.equal(entries.get('value.PACK_INFO.0'), 'Made with TexturesOnline');
    // Every value label refers to a value that exists.
    for (const key of entries.keys()) {
      const m = /^value\.(\w+)\.(.+)$/.exec(key);
      if (!m) continue;
      const o = opts.values.get(m[1]);
      assert.ok(o && o.list.includes(m[2]), `${name}: ${key} labels an existing value`);
    }
  }
});

/** IDs the GLSL compares against (const ID_* / BE_* / ENTITY_* / ITEM_* in common.glsl). */
function glslIds(files: Files): { block: Set<number>; entity: Set<number>; item: Set<number> } {
  const common = files['shaders/lib/common.glsl'];
  const block = new Set<number>();
  const entity = new Set<number>();
  const item = new Set<number>();
  for (const m of common.matchAll(/const (?:float|int) (ID_\w+|BE_\w+|ENTITY_\w+|ITEM_\w+)\s*=\s*(\d+)(?:\.0)?;/g)) {
    const id = Number(m[2]);
    if (m[1].startsWith('ENTITY_')) entity.add(id);
    else if (m[1].startsWith('ITEM_')) item.add(id);
    else block.add(id);
  }
  return { block, entity, item };
}

test('block.properties: IDs 10001-10020 consistent with the GLSL for every game version', () => {
  const files = gen(defaults());
  const text = files['shaders/block.properties'];
  const ids = glslIds(files);
  assert.deepEqual([...ids.block].sort(), Object.entries(IRIS_IDS).filter(([k]) => !/^(lightning|item)/.test(k)).map(([, v]) => v).sort());
  for (const line of text.split('\n')) {
    assert.ok(!line.trimEnd().endsWith('\\'), 'no line continuations');
    if (line.startsWith('block.')) assert.ok(!line.includes('%') || line.includes('%minecraft:'), line.slice(0, 40));
  }
  const envs: Array<[string, Record<string, string>, boolean]> = [
    ['iris 26.3', { MC_VERSION: '260300', IS_IRIS: '', IRIS_TAG_SUPPORT: '2' }, true],
    ['iris 1.20.2', { MC_VERSION: '12002', IS_IRIS: '', IRIS_TAG_SUPPORT: '2' }, true],
    ['iris 1.16.5', { MC_VERSION: '11605', IS_IRIS: '' }, true],
    ['optifine 1.21.11', { MC_VERSION: '12111' }, true],
    ['optifine 1.12.2', { MC_VERSION: '11202' }, false],
    ['optifine 1.8.9', { MC_VERSION: '10809' }, false],
  ];
  for (const [env, macros, modern] of envs) {
    const entries = propertiesFor(text, macros);
    const keys = entries.map(([k]) => k);
    assert.equal(new Set(keys).size, keys.length, `${env}: every block.N key once`);
    const found = new Set<number>();
    const seenBlocks = new Map<string, number>();
    for (const [key, value] of entries) {
      const m = /^block\.(\d+)$/.exec(key);
      assert.ok(m, `${env}: unexpected key ${key}`);
      const id = Number(m[1]);
      assert.ok(id >= 10001 && id <= 10020, `${env}: ID ${id} in 10001-10020`);
      assert.ok(ids.block.has(id), `${env}: ID ${id} is used by the GLSL`);
      found.add(id);
      const names = value.split(/\s+/);
      assert.ok(names.length > 0 && names.every((n) => /^%?minecraft:[a-z0-9_]+(:[a-z_]+=[a-z0-9_,]+)*$/.test(n)), `${env}: block.${id} syntax`);
      for (const n of names) {
        const plain = n.replace(/^%/, '');
        assert.ok(!seenBlocks.has(plain) || seenBlocks.get(plain) === id, `${env}: ${plain} under two IDs`);
        seenBlocks.set(plain, id);
      }
      if (!modern) assert.ok(!names.some((n) => n.startsWith('%')), `${env}: no tags on legacy versions`);
    }
    assert.deepEqual([...found].sort(), [...ids.block].sort(), `${env}: every GLSL ID is mapped`);
    const leaves = entries.find(([k]) => k === 'block.10001')![1];
    const plants = entries.find(([k]) => k === 'block.10002')![1];
    if (modern) {
      assert.ok(leaves.includes('minecraft:oak_leaves'));
      assert.equal(leaves.includes('%minecraft:leaves'), 'IRIS_TAG_SUPPORT' in macros, `${env}: tags only with IRIS_TAG_SUPPORT`);
      const v = Number(macros.MC_VERSION);
      assert.equal(plants.includes('minecraft:short_grass'), v >= 12003, `${env}: short_grass`);
      assert.equal(/minecraft:grass( |$)/.test(plants), v < 12003, `${env}: grass`);
    } else {
      assert.ok(leaves.includes('minecraft:leaves2'));
      assert.ok(plants.includes('minecraft:tallgrass'));
    }
  }
});

test('item.properties / entity.properties match the IDs the GLSL uses', () => {
  const files = gen(defaults());
  const ids = glslIds(files);
  const items = propertiesFor(files['shaders/item.properties'], { MC_VERSION: '260300' });
  assert.deepEqual(items.map(([k]) => Number(k.replace('item.', ''))).sort(), [...ids.item].sort());
  assert.ok(items.some(([, v]) => v.includes('minecraft:lava_bucket')));
  for (const [, v] of items) assert.ok(!v.includes(':', v.indexOf(':') + 1) || v.split(' ').every((x) => x.split(':').length === 2), 'items have no states');
  const entities = propertiesFor(files['shaders/entity.properties'], { MC_VERSION: '260300' });
  assert.deepEqual(entities.map(([k]) => Number(k.replace('entity.', ''))).sort(), [...ids.entity].sort());
  assert.ok(entities.some(([, v]) => v.includes('minecraft:lightning_bolt')));
  // The item and entity IDs are compared against the matching uniforms.
  assert.ok(files['shaders/lib/lighting.glsl'].includes('heldItemId == ITEM_BRIGHT_LIGHT'));
  assert.ok(files['shaders/gbuffers_entities.fsh'].includes('entityId == ENTITY_LIGHTNING'));
  assert.ok(files['shaders/gbuffers_block.fsh'].includes('blockEntityId == BE_END_PORTAL'));
});

test('zipIrisPack: shaders/ at the root with directory entries; readable by the app zip reader', async () => {
  const files = gen(presetValues('fantasy'));
  const zip = zipIrisPack(files, { mtime: new Date('2026-01-01T00:00:00Z') });
  const entries = unzipSync(zip);
  const names = Object.keys(entries);
  for (const dir of ['shaders/', 'shaders/lib/', 'shaders/lang/']) {
    assert.ok(names.includes(dir), `directory entry ${dir}`);
    assert.equal(entries[dir].length, 0);
  }
  const fileNames = names.filter((n) => !n.endsWith('/'));
  assert.deepEqual(fileNames.sort(), Object.keys(files).sort());
  for (const n of fileNames) assert.equal(strFromU8(entries[n]), files[n], n);
  const tops = new Set(names.map((n) => n.split('/')[0] + (n.includes('/') ? '/' : '')));
  assert.deepEqual([...tops].sort(), ['README.txt', 'shaders/']);
  // Same bytes for the same input and timestamp.
  assert.deepEqual(zipIrisPack(files, { mtime: new Date('2026-01-01T00:00:00Z') }), zip);
  const back = await readZip(zip);
  assert.deepEqual(Object.keys(back).sort(), Object.keys(files).sort());
  // The generic app writer works too (it just has no directory entries).
  const blob = await writeZip(files);
  const plain = unzipSync(new Uint8Array(await blob.arrayBuffer()));
  assert.equal(strFromU8(plain['shaders/final.fsh']), files['shaders/final.fsh']);
  assert.throws(() => zipIrisPack({ 'a/b': 'x', 'a/b/c': 'y' }));
});

test('deterministic output, safe metadata and file names', () => {
  assert.deepEqual(gen(presetValues('golden')), gen(presetValues('golden')));
  const empty = gen(defaults(), { name: '   ', description: '' });
  assert.ok(empty['shaders/lang/en_US.lang'].includes('option.PACK_INFO=TexturesOnline Shaders\n'));
  assert.ok(empty['shaders/lang/en_US.lang'].includes('option.PACK_INFO.comment=Made with TexturesOnline.\n'));
  const weird = gen(defaults(), { name: '#!  Evil=Name\\with%stuff', description: '*/ /* end' });
  assert.ok(weird['shaders/lang/en_US.lang'].includes('option.PACK_INFO=Evil=Namewithstuff\n'));
  for (const p of shaderFiles(weird)) {
    if (/\.(glsl|vsh|fsh|properties)$/.test(p) && weird[p].includes('Evil')) {
      const line = weird[p].split('\n').find((l) => l.includes('Evil'))!;
      assert.match(line, /^(\/\/|#) [ -~]*$/, `${p}: the name only appears in a plain comment line`);
      assert.ok(!/[\\*%]/.test(line), `${p}: no backslash, * or % in the comment`);
    }
  }
  const long = gen(defaults(), { name: 'x'.repeat(500), description: 'y'.repeat(5000) });
  assert.ok(long['shaders/lang/en_US.lang'].includes(`option.PACK_INFO=${'x'.repeat(64)}\n`));
  assert.equal(irisPackFileName('My Shaders'), 'My Shaders.zip');
  assert.equal(irisPackFileName('a/b:c*?'), 'a_b_c_.zip');
  assert.equal(irisPackFileName(''), 'TexturesOnline Shaders.zip');
  assert.equal(irisPackFileName('pack.zip'), 'pack.zip');
  // Invalid input never breaks generation.
  const garbage = gen({ sunStrength: 'abc', tonemap: 42, skyColor: null } as unknown as OptionValues);
  assert.deepEqual(parsePackOptions(garbage).problems, []);
});
