/**
 * Audit: resolves every block (and every state of it) of a Java version or Bedrock and reports the
 * ones that fall back to a flat texture sheet, have no geometry, reference missing textures in any
 * state, or are only approximated; plus how items are drawn.
 * Usage: TO_FIXTURES=<dir> npx tsx tests/tools/models/audit.ts [26.3|1.20.1|...|bedrock] [--states] [--items] [--no-java]
 * Bedrock takes its built-in shapes from the 26.3 jar's block models (--no-java: without them).
 */
import { loadModelLibrary, type ModelEntry, type ModelLibrary, type ModelView, type BlockState } from '../../../src/shared/models/index';
import { bedrockAssets, javaJarAssets, javaModelJson } from './fixtures';

const which = process.argv[2] ?? '26.3';
const allStates = process.argv.includes('--states');
const withItems = process.argv.includes('--items');
const bedrock = which === 'bedrock';
const assets = bedrock ? bedrockAssets() : javaJarAssets(which);
if (!assets) {
  console.error('fixtures missing (set TO_FIXTURES)');
  process.exit(2);
}
const java = bedrock && !process.argv.includes('--no-java') ? javaModelJson('26.3') : null;
const lib: ModelLibrary = await loadModelLibrary(assets, bedrock ? { javaModels: async () => java } : {});

/** Armor trim textures are generated by the game from palettes: they never exist as files. */
const generated = (p: string) => /\/trims\/items\//.test(p);
const missingOf = (v: ModelView): string[] => [
  ...new Set([
    ...v.quads.filter((q) => !q.texture || (!assets.hasFile(q.texture) && !generated(q.texture))).map((q) => q.texture ?? `(unresolved ${q.ref})`),
    ...v.sprite.filter((s) => !assets.hasFile(s.path) && !generated(s.path)).map((s) => s.path),
  ]),
];

/** The default state plus every single-property change of it (and every pair when there are few). */
function statesOf(e: ModelEntry): BlockState[] {
  const base = lib.defaultState(e);
  const props = lib.properties(e);
  const out: BlockState[] = [base];
  for (const p of props) for (const v of p.values) if (base[p.name] !== v.value) out.push({ ...base, [p.name]: v.value });
  const total = props.reduce((n, p) => n * p.values.length, 1);
  if (total <= 256) {
    let combos: BlockState[] = [{}];
    for (const p of props) combos = combos.flatMap((c) => p.values.map((v) => ({ ...c, [p.name]: v.value })));
    out.push(...combos.map((c) => ({ ...base, ...c })));
  }
  return out;
}

const blocks = lib.blocks();
const buckets: Record<string, string[]> = { special: [], invisible: [], sprite: [], empty: [], missingTex: [], approximate: [], stateMissing: [], stateEmpty: [], ok: [] };
const notes = new Map<string, string>();
let statesChecked = 0;
for (const e of blocks) {
  const v = lib.resolve(e, lib.defaultState(e));
  if (v.note) notes.set(e.id, v.note);
  const missing = missingOf(v);
  if (v.shape === 'special') buckets.special.push(e.id);
  else if (v.shape === 'sprite' && v.category === 'special') buckets.invisible.push(e.id);
  else if (v.shape === 'sprite') buckets.sprite.push(e.id);
  else if (!v.quads.length) buckets.empty.push(e.id);
  else if (missing.length) buckets.missingTex.push(`${e.id} (${missing.join(', ')})`);
  else if (v.approximate) buckets.approximate.push(e.id);
  else buckets.ok.push(e.id);
  if (allStates && v.shape !== 'special') {
    let reported = false;
    for (const st of statesOf(e)) {
      statesChecked++;
      const s = lib.resolve(e, st);
      if (s.shape === 'model' && !s.quads.length && !reported) {
        buckets.stateEmpty.push(`${e.id} ${JSON.stringify(st)}`);
        reported = true;
      }
      const m = missingOf(s);
      if (m.length && !reported) {
        buckets.stateMissing.push(`${e.id} ${JSON.stringify(st)} (${m.join(', ')})`);
        reported = true;
      }
    }
  }
}
console.log(`${which}: ${blocks.length} blocks${allStates ? `, ${statesChecked} states checked` : ''}${bedrock ? (java ? ' (shapes from Java 26.3 models)' : ' (no Java models)') : ''}`);
for (const [k, list] of Object.entries(buckets)) {
  if (k === 'ok') console.log(`ok: ${list.length}`);
  else console.log(`\n${k} (${list.length}):\n  ${list.join('\n  ')}`);
}
const noteGroups = new Map<string, string[]>();
for (const [id, n] of notes) noteGroups.set(n, [...(noteGroups.get(n) ?? []), id]);
console.log('\nnotes:');
for (const [n, ids] of noteGroups) console.log(`  [${ids.length}] ${n}\n     ${ids.slice(0, 12).join(', ')}${ids.length > 12 ? ' ...' : ''}`);

if (withItems) {
  const items: Record<string, string[]> = { sprite: [], model: [], special: [], empty: [], missingTex: [] };
  for (const e of lib.items()) {
    const n = Math.max(1, lib.properties(e)[0]?.values.length ?? 1);
    for (let i = 0; i < n; i++) {
      const v = lib.resolve(e, n > 1 ? { model: String(i) } : {});
      const tag = n > 1 ? `${e.id}#${i}` : e.id;
      const missing = missingOf(v);
      if (missing.length) items.missingTex.push(`${tag} (${missing.join(', ')})`);
      if (i > 0) continue;
      if (v.shape === 'special') items.special.push(tag);
      else if (v.shape === 'sprite') items.sprite.push(tag);
      else if (!v.quads.length) items.empty.push(tag);
      else items.model.push(tag);
    }
  }
  console.log(`\nitems: ${lib.items().length}`);
  for (const [k, list] of Object.entries(items)) console.log(`  ${k}: ${list.length}${k === 'sprite' || k === 'model' ? '' : `\n    ${list.join('\n    ')}`}`);
}
